import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Thread Afair</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="header">Hello mofo</header>

      <main className="content"></main>

      <footer className="footer"></footer>
    </div>
  );
}
